#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
env:
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  CONFIG_PATH: config
  CONFIG_SH: config.sh
  KERNEL: 3.4
  TNAME: ""
  
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone source code
      run: |
        chmod +x $CONFIG_SH
        $GITHUB_WORKSPACE/$CONFIG_SH
        echo $env.KERNEL
        echo $env.TNAME
        cat $CONFIG_PATH/${{env.TNAME}}.sh
